INSERT INTO userProfile (userID, username, avatar, bio, profileColor, activityStatus, lastConnexion) VALUES (1, 'Hugues', 'avatar1.png', 'Bio of alex', 'white', 1, '2025-09-04 13:00:00');
INSERT INTO userProfile (userID, username, avatar, bio, profileColor, activityStatus, lastConnexion) VALUES (2, 'alex', 'avatar1.png', 'Bio of Hugues', 'black', 2, '2025-09-04 13:00:00');
INSERT INTO userProfile (userID, username, avatar, bio, profileColor, activityStatus, lastConnexion) VALUES (3, 'Coralie', 'avatar1.png', 'Bio of Coralie', 'green', 2, '2025-09-04 13:00:00');
INSERT INTO userProfile (userID, username, avatar, bio, profileColor, activityStatus, lastConnexion) VALUES (4, 'Charlotte', 'avatar1.png', 'Bio of Charlotte', 'purple', 2, '2025-09-04 13:00:00');
INSERT INTO userProfile (userID, username, avatar, bio, profileColor, activityStatus, lastConnexion) VALUES (5, 'Sam', 'avatar1.png', 'Bio of Sam', 'red', 2, '2025-09-04 13:00:00');
INSERT INTO userStats (userID, longestMatch, shorestMatch, totalMatch, totalWins, winStreak, averageMatchDuration, highestScore) VALUES (1, 120, 30, 10, 6, 3, 60, 200);
INSERT INTO userStats (userID, longestMatch, shorestMatch, totalMatch, totalWins, winStreak, averageMatchDuration, highestScore) VALUES (2, 120, 30, 10, 6, 3, 60, 200);
INSERT INTO userStats (userID, longestMatch, shorestMatch, totalMatch, totalWins, winStreak, averageMatchDuration, highestScore) VALUES (3, 120, 30, 10, 6, 3, 60, 200);
INSERT INTO userStats (userID, longestMatch, shorestMatch, totalMatch, totalWins, winStreak, averageMatchDuration, highestScore) VALUES (4, 120, 30, 10, 6, 3, 60, 200);
INSERT INTO userStats (userID, longestMatch, shorestMatch, totalMatch, totalWins, winStreak, averageMatchDuration, highestScore) VALUES (5, 120, 30, 10, 6, 3, 60, 200);