components:
  responses:
    BadRequest:
      content:
        application/json:
          example:
            code: 400
            message: Malformed parameters could not be processed
          schema:
            $ref: "#/components/schemas/error"
      description: Bad Request
    Forbidden:
      content:
        application/json:
          example:
            code: 403
            message: You are not authorized to access this ressource
          schema:
            $ref: "#/components/schemas/error"
      description: Forbidden
    MethodNotAllowed:
      content:
        application/json:
          example:
            code: 405
            message: This operation is not allowed on this ressource
          schema:
            $ref: "#/components/schemas/error"
      description: Unsupported request
    NotFound:
      content:
        application/json:
          example:
            code: 404
            message: User not found
          schema:
            $ref: "#/components/schemas/error"
      description: Not Found
    Success:
      content:
        application/json:
          example:
            code: 200
          schema:
            $ref: "#/components/schemas/success"
      description: Signals the operation was successful

    Unauthorized:
      content:
        application/json:
          example:
            code: 401
            message: You are not authorized to access this ressource; try login in.
          schema:
            $ref: "#/components/schemas/error"
      description: Unauthorized (should redirect on login screen)
  schemas:
    avatar:
      description: a binary representation of the user's avatar
      example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
      format: binary
      type: string
    biography:
      description: the user's chosen biography
      example: '¯\_(ツ)_/¯'
      maxLength: 180
      type: string
    credentials:
      description: the registering user informations to validate.
      properties:
        nickname:
          $ref: "#/components/schemas/nickname"
        password:
          $ref: "#/components/schemas/password"
      type: object
    duration:
      description: start and end times of a match in ISO 8601 format
      properties:
        begin_at:
          description: ISO 8601 date at which the game started
          example: 2025-07-30T12:46:48Z
          format: date-time
          type: string
        end_at:
          description: ISO 8601 date at which the game ended
          example: 2025-07-30T12:47:13Z
          format: date-time
          type: string
        sec_duration:
          description: a match duration in seconds
          example: 25
          format: integer
          type: number
      required:
        - begin_at
        - end_at
        - sec_duration
      type: object
    email:
      example: ja.pankraz@oxenfurt.re.edu
      format: email
      type: string
    error:
      properties:
        code:
          description: the value of the error code
          format: integer
          type: number
        details:
          description: more information on the error
          type: string
        message:
          description: a human-readable message describing the error
          type: string
      required:
        - code
        - message
      type: object
    game_history:
      description: an array of the user's matches
      items:
        $ref: "#/components/schemas/match"
      type: array
    game_stats:
      description: precomputed stats about the user's game history
      properties:
        longest_match:
          $ref: "#/components/schemas/duration"
        longest_pass:
          description: longest exchange without dropping the ball or scoring a goal
          example: 25
          format: integer
          type: number
        nemesis:
          $ref: "#/components/schemas/user"
        shortest_match:
          $ref: "#/components/schemas/duration"
        total_games:
          description: the total number of matches the user ever played
          example: 32
          format: integer
          type: number
        total_loss:
          description: the total number of matches the user ever lost
          example: 12
          format: integer
          type: number
        total_win:
          description: the total number of matches the user ever won
          example: 20
          format: integer
          type: number
        winstreak:
          description: most matches won in a row
          example: 10
          format: integer
          type: number
      required:
        - total_games
        - total_win
        - total_loss
        - longest_pass
        - winstreak
        - longest_match
        - shortest_match
        - nemesis
      type: object
    joined_on:
      description: date of the user's profile creation
      example: 2025-08-07T13:00:00Z
      format: date-time
      type: string
    loser:
      description: looser for the specified match
      example: "looserLoon"
      type: string
    match:
      description: a single match
      properties:
        duration:
          $ref: "#/components/schemas/duration"
        loser:
          $ref: "#/components/schemas/loser"
        score:
          $ref: "#/components/schemas/score"
        winner:
          $ref: "#/components/schemas/winner"
      required:
        - winner
        - loser
        - duration
        - score
      type: object
    nickname:
      description: the user's chosen nickname
      example: "Dandelion"
      maxLength: 12
      minLength: 4
      type: string
    password:
      description: |
        the user's password. It must be at least 12 characters long, and contain:
        - at least one **uppercase letter** [A-Z]
        - at least one **lowercase letter** [a-z]
        - at least one **digit** [0 - 9]
        - at least one **special characters** [@ $ ! % * ? &]
      example: $FillinglessPie1249%
      format: password
      minLength: 12
      pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{12,}$
      type: string
    profile:
      description: a user's profile
      properties:
        game_history:
          $ref: "#/components/schemas/game_history"
        game_stats:
          $ref: "#/components/schemas/game_stats"
        user:
          $ref: "#/components/schemas/user"
      required:
        - user
        - game_history
        - game_stats
      type: object
    profile_color:
      description: the user's profile main color scheme
      example: ff69b4
      type: string
    score:
      additionalProperties:
        description: the mapped user's score in numeric value
        type: number
      description: a map of player names to their scores.
      example:
        looserLoon: 2
        winningWolf: 5
      type: object
    sessionToken:
      description: a JWT representation of a user session
      properties:
        expiresAt:
          description: absolute time at which the token will become obsolete
          example: 2025-07-30T12:46:48Z
          format: date-time
          type: string
        expiresIn:
          description: time until expiration of the current session in seconds
          example: 3600
          format: integer
          type: number
        refreshToken:
          $ref: "#/components/schemas/token"
          description: |
            Refresh token to handle seamless user sessions.
        sessionId:
          $ref: "#/components/schemas/token"
          description: |
            The Bearer token associated to the current session.
            It is stored as a cookie in the browser, and internally handled for CLI users.

      required:
        - sessionId
        - tokenType
        - expiresIn
      type: object
    settings:
      description: the user's personnal informations
      properties:
        avatar:
          $ref: "#/components/schemas/avatar"
        biography:
          $ref: "#/components/schemas/biography"
        email:
          $ref: "#/components/schemas/email"
        nickname:
          $ref: "#/components/schemas/nickname"
        profile_color:
          $ref: "#/components/schemas/profile_color"
      required:
        - nickname
        - avatar
        - email
      type: object
    settingsPatch:
      description: the user's personnal informations
      properties:
        avatar:
          $ref: "#/components/schemas/avatar"
        biography:
          $ref: "#/components/schemas/biography"
        email:
          $ref: "#/components/schemas/email"
        nickname:
          $ref: "#/components/schemas/nickname"
        password:
          $ref: "#/components/schemas/password"
        profile_color:
          $ref: "#/components/schemas/profile_color"
      type: object
    status:
      description: indicates whether the user is currently online
      type: boolean
    success:
      description: signals the operation's success
      properties:
        code:
          description: the value of the success code
          format: integer
          type: number
      required:
        - code
      type: object

    token:
      description: JWT for session management.
      properties:
        type:
          enum:
            - Bearer
            - Refresh
          example: "bearer || refresh"
        value:
          example: "iVBORw0KGgoAAAANSUhEUgAA... token"
          type: string
      type: object
    tournament:
      description: a tournament object with associated matches and outcomes
      properties:
        matches:
          description: an array containing the tournament's matches
          items:
            $ref: "#/components/schemas/match"
          type: array
      required:
        - matches
      type: object
    user:
      description: a succint user's profile card
      properties:
        avatar:
          $ref: "#/components/schemas/avatar"
        biography:
          $ref: "#/components/schemas/biography"
        joined_on:
          $ref: "#/components/schemas/joined_on"
        nickname:
          $ref: "#/components/schemas/nickname"
        profile_color:
          $ref: "#/components/schemas/profile_color"
        rank:
          description: the user's rank in competitive pong games
          example: Gold
          type: string
        status:
          $ref: "#/components/schemas/status"
      required:
        - avatar
        - nickname
        - profile_color
        - rank
        - status
      type: object
    winner:
      description: winner for the specified match
      example: "winningWolf"
      type: string

  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt

info:
  description: Documentation for the RESTful section the BigTeam's Transcendance project
  title: BigTeam API
  version: 1.0.0
openapi: 3.1.0

paths:
  /user/friends:
    get:
      description: |
        Return an object containing the validated friends of the user identified by their token.
      summary: returns a user's friend list
      tags:
        - friends
      security:
        - bearerAuth: []
        - cookieAuth: []
    # post:

    # patch:

  /account:
    post:
      description: |
        Creates a new persistent or temporary user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
        required: true
      responses:
        "201":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
      summary: registers a new user
      tags:
        - account management
    delete:
      description: |
        Deletes an user account and all associated information. <br>
        The server will determine the account to be deleted based on the user ID contained in the JWT.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
        required: true
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
      security:
        - cookieAuth: []
        - bearerAuth: []
      summary: deletes an authenticated user account
      tags:
        - account management

  /auth/browser:
    post:
      description: |
        Allows browser based users to authenticate using JWT<br>
        It is stored in a HTTPOnly, Secure, Same-Site cookie.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
        required: true
      responses:
        "204":
          description: |
            Upon success, server sends a JWT Token to the client. <br>
            It is stored automatically in a secure cookie (HTTP Only, Secure, Same-Site)
          headers:
            Set-Cookie:
              description: |
                Session cookie containing the session token. <br>
                Security attributes include: HTTP Only, Secure, Same-Site
              example: jwt=abc123; Path=/; HttpOnly; Secure; SameSite=Strict
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      summary: generates an authentication token for browser users
      tags:
        - authentication
  /auth/cli:
    post:
      tags:
        - authentication
      description: |
        Allows CLI based users to authenticate using a JWT. <br>
        The JWT must be handled manually on the client side.
      summary: generates an authentication token for CLI users
  
  # /jwt/invalidate:
  # deletes a client's JWT from the browser

  # /jwt/refresh
  # refreshes the user's session using the JWT refresh token.
  /user/settings:
    get:
      description: |
        Returns the settings for the user, as identified by their token.
        A user will only be able to access their own setting, never that of another user.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/settings"
          description: Returns a user's profile (profile card, match history, game_stats)
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
      security:
        - bearerAuth: []
        - cookieAuth: []
      summary: get user's settings by ID
      tags:
        - users
    patch:
      description: |
        Sends a request to the user database to update given informations. <br>
        Informations can be modified individually or in batches.
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: "#/components/schemas/settingsPatch"
        required: true
      responses:
        "200":
          $ref: "#/components/responses/Success"
          description: returns confirmation of the updated informations
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
      security:
        - bearerAuth: []
      summary: update user's personnal information by ID
      tags:
        - users
  /users/{id}:
    get:
      description: |
        Returns the public profile informations for the user specified by ID.

        All users may access other users public profiles.
      parameters:
        - example: angryGoose
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
          description: |
            Returns a user's profile (profile card, match history, game_stats) to be rendered for the UI
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
      summary: get user's profile by ID
      tags:
        - users

servers:
  - description: Our lone server, we don't really need a production one
    url: https://localhost:8443
