openapi: 3.1.1

info:
  title: BigTeam API
  description: Documentation for the RESTful section the BigTeam's Transcendance project
  version: 1.0.0

servers:
  - url: https://localhost:8443
    description: Our lone server, we don't really need a production one

paths:
  /users/{id}:
    get:
      summary: get user's profile by ID
      description: |
        Returns the public profile informations for the user specified by ID.

        All users may access other users public profiles.
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: angryGoose
      responses:
        "200":
          description: |
            Returns a user's profile (profile card, match history, game_stats) to be rendered for the UI
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"

  /user/{id}/settings:
    get:
      summary: get user's settings by ID
      description: |
        Returns the settings for the user specified by ID. 

        It will always return the settings for the user that is currently logged.
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: angryGoose
      responses:
        "200":
          description: Returns a user's profile (profile card, match history, game_stats)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/settings"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
    patch:
      security:
        - bearerAuth: []
      tags:
        - users
      summary: update user's personnal information by ID
      description: |
        Sends a request to the user database to update given informations.

        Informations can be modified individually or in batches.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: angryGoose
      requestBody:
        required: true
        content:
          application/json-patch+json:
            schema:
              $ref: "#/components/schemas/settingsPatch"
      responses:
        "200":
          description: returns confirmation of the updated informations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/settings"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/MethodNotAllowed"
  /register:
    post:
      tags:
        - auth
      summary: register a new user
      description: |
        Sends a post request to create a new persistent or temporary user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
  /sessions:
    post:
      tags:
        - auth
      summary: create a new user session
      description: |
        Allows the user to log to the app by creating a new session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # user schemas
    # plain
    avatar:
      description: a binary representation of the user's avatar
      example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
      format: binary
      type: string
    biography:
      description: the user's chosen biography
      example: '¯\_(ツ)_/¯'
      maxLength: 180
      type: string
    email:
      example: ja.pankraz@oxenfurt.re.edu
      format: email
      type: string
    joined_on:
      description: date of the user's profile creation
      example: 2025-08-07T13:00:00Z
      format: date-time
      type: string
    nickname:
      description: the user's chosen nickname
      example: "Dandelion"
      maxLength: 12
      minLength: 4
      type: string
    profile_color:
      description: the user's profile main color scheme
      example: ff69b4
      type: string

    # auth schemas
    # plain
    password:
      description: |
        the user's password. It must be at least 12 characters long, and contain:
        - at least one **uppercase letter** [A-Z]
        - at least one **lowercase letter** [a-z]
        - at least one **digit** [0 - 9]
        - at least one **special characters** [@ $ ! % * ? &]
      type: string
      format: password
      minLength: 12
      pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$
      example: $FillinglessPie1249%
    # composite
    credentials:
      type: object
      description: the registering user informations to validate.
      properties:
        nickname:
          $ref: "#/components/schemas/nickname"
        password:
          $ref: "#/components/schemas/password"

    # game schemas
    winner:
      type: string
      description: winner for the specified match
      example: "winningWolf"
    loser:
      type: string
      description: looser for the specified match
      example: "looserLoon"
    status:
      type: boolean
      description: indicates whether the user is currently online
    duration:
      type: object
      description: start and end times of a match in ISO 8601 format
      properties:
        begin_at:
          type: string
          format: date-time
          description: ISO 8601 date at which the game started
          example: 2025-07-30T12:46:48Z
        end_at:
          type: string
          format: date-time
          description: ISO 8601 date at which the game ended
          example: 2025-07-30T12:47:13Z
        sec_duration:
          type: number
          format: integer
          description: a match duration in seconds
          example: 25
      required:
        - begin_at
        - end_at
        - sec_duration
    score:
      type: object
      description: a map of player names to their scores.
      additionalProperties:
        type: number
        description: the mapped user's score in numeric value
      example:
        winningWolf: 5
        looserLoon: 2
    match:
      type: object
      description: a single match
      properties:
        winner:
          $ref: "#/components/schemas/winner"
        loser:
          $ref: "#/components/schemas/loser"
        duration:
          $ref: "#/components/schemas/duration"
        score:
          $ref: "#/components/schemas/score"
      required:
        - winner
        - loser
        - duration
        - score
    tournament:
      type: object
      description: a tournament object with associated matches and outcomes
      properties:
        matches:
          type: array
          description: an array containing the tournament's matches
          items:
            $ref: "#/components/schemas/match"
      required:
        - matches
    game_history:
      type: array
      description: an array of the user's matches
      items:
        $ref: "#/components/schemas/match"
    game_stats:
      type: object
      description: precomputed stats about the user's game history
      properties:
        total_games:
          type: number
          format: integer
          description: the total number of matches the user ever played
          example: 32
        total_win:
          type: number
          format: integer
          description: the total number of matches the user ever won
          example: 20
        total_loss:
          type: number
          format: integer
          description: the total number of matches the user ever lost
          example: 12
        longest_pass:
          type: number
          format: integer
          description: longest exchange without dropping the ball or scoring a goal
          example: 25
        winstreak:
          type: number
          format: integer
          description: most matches won in a row
          example: 10
        longest_match:
          $ref: "#/components/schemas/duration"
        shortest_match:
          $ref: "#/components/schemas/duration"
        nemesis:
          $ref: "#/components/schemas/user"
      required:
        - total_games
        - total_win
        - total_loss
        - longest_pass
        - winstreak
        - longest_match
        - shortest_match
        - nemesis
    user:
      type: object
      description: a succint user's profile card
      properties:
        nickname:
          $ref: "#/components/schemas/nickname"
        avatar:
          $ref: "#/components/schemas/avatar"
        status:
          $ref: "#/components/schemas/status"
        biography:
          $ref: "#/components/schemas/biography"
        profile_color:
          $ref: "#/components/schemas/profile_color"
        joined_on:
          $ref: "#/components/schemas/joined_on"
        rank:
          type: string
          description: the user's rank in competitive pong games
          example: Gold
      required:
        - avatar
        - nickname
        - profile_color
        - rank
        - status
    profile:
      type: object
      description: a user's profile
      properties:
        user:
          $ref: "#/components/schemas/user"
        game_history:
          $ref: "#/components/schemas/game_history"
        game_stats:
          $ref: "#/components/schemas/game_stats"
      required:
        - user
        - game_history
        - game_stats

    settings:
      type: object
      description: the user's personnal informations
      properties:
        nickname:
          $ref: "#/components/schemas/nickname"
        avatar:
          $ref: "#/components/schemas/avatar"
        biography:
          $ref: "#/components/schemas/biography"
        profile_color:
          $ref: "#/components/schemas/profile_color"
        email:
          $ref: "#/components/schemas/email"
      required:
        - nickname
        - avatar
        - email
    settingsPatch:
      type: object
      description: the user's personnal informations
      properties:
        nickname:
          $ref: "#/components/schemas/nickname"
        avatar:
          $ref: "#/components/schemas/avatar"
        biography:
          $ref: "#/components/schemas/biography"
        profile_color:
          $ref: "#/components/schemas/profile_color"
        password:
          $ref: "#/components/schemas/password"
        email:
          $ref: "#/components/schemas/email"

    error:
      type: object
      properties:
        code:
          type: number
          format: integer
          description: the value of the error code
        message:
          type: string
          description: a human-readable message describing the error
        details:
          type: string
          description: more information on the error
      required:
        - code
        - message
      example:
        code: 404
        message: User does not exist
        details: Requested bad user 'angryGoose_314'
    success:
      type: object
      properties:
        code:
          type: number
          format: integer
          description: the value of the success code
        message:
          type: string
          description: validation of the operation's success
      required:
        - code
        - message
      example:
        code: 200
        message: created user Dandelion successfully

  responses:
    Success:
      description: Operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/success"

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    Unauthorized:
      description: Unauthorized (should redirect on login screen)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    MethodNotAllowed:
      description: Unsupported request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
