INSERT INTO translations (word, language_code, translation) VALUES
  ('Play', 'en', 'Play'),
  ('Central', 'en', 'central'),
  ('Tournament', 'en', 'Tournament'),
  ('Profile', 'en', 'Profile'),
  ('Quick Match', 'en', 'Quick Match'),
  ('Game', 'en', 'Game'),
  ('Leaderboard', 'en', 'Leaderboard'),
  ('Account Settings', 'en', 'Account Settings'),
  ('Edit Profile', 'en', 'Edit Profile'),
  
  ('Play', 'es', 'Jugar'),
  ('Central', 'es', 'central'),
  ('Tournament', 'es', 'Torneo'),
  ('Profile', 'es', 'Perfil'),
  ('Quick Match', 'es', 'Parte Rápida'),
  ('Game', 'es', 'Juego'),
  ('Leaderboard', 'es', 'Junta de líderes'),
  ('Account Settings', 'es', 'Configuraciones de la cuenta'),
  ('Edit Profile', 'es', 'Editar perfil'),
  
  ('Play', 'fr', 'Jouer'),
  ('Central', 'fr', 'central'),
  ('Tournament', 'fr', 'Tournoi'),
  ('Profile', 'fr', 'Profil'),
  ('Quick Match', 'fr', 'Partie Rapide'),
  ('Game', 'fr', 'Jeu'),
  ('Leaderboard', 'fr', 'Board des leaders'),
  ('Account Settings', 'fr', 'Parametres du compte'),
  ('Edit Profile', 'fr', 'Modifier le profil');