---
config:
  theme: redux-dark-color
  look: classic
---
sequenceDiagram

  title JSON Web Tokens

  participant B as Browser
  participant A as JWT Auth
  participant G as NGINX Gateway
  participant GM as GameManager
  participant F as Friends
  participant D as Database
  autonumber

  B ->> A: Login (credentials)
  A -->> B: Return JWT
  B ->> G: API Request (with JWT)
  G ->> G: Validate JWT
  G ->> G: Check basic authorisation
  alt Game Request
    G ->> GM: Route to GM
    GM ->> F: Check user authorisation
    GM ->> D: Update/Retrieve Game Data
    GM -->> G: Response (game event)
  end
  alt Friend Request
    G ->> F: Route to Friends
    F ->> F: Check user authorisation
    F ->> D: Update/Retrieve Friend Data
    F -->> G: Response (friend event)
  end
  G -->> B: API Response
  B ->> B: Display result
