sequenceDiagram
    title GameManager (tournament)
    autonumber

    create actor C as Client
    create participant Pre as PreGame
    C-)Pre: OPEN connection (WS)
    C-)Pre: request TOURNAMENT_LOBBY + send JSON.userInfo (WS)
    C->>C: Show "Creating lobby..."
    Pre->>Pre: Create LOBBY with host inside
    Pre->>Pre: Invite other players
    Pre->>Pre: Choose game rules
    Pre->>Pre: Start TOURNAMENT
    create participant P as Pong
    Pre-)P: send pregame.remote.4.create (NATS)
    Pre--)C: send match found (WS)
    C->>C: Show "Match found!"
    Pre->>Pre: receive match object
    Pre-)P: send match object to game.ready (NATS)
    P--)Pre: send game.waiting (NATS)
    Pre--)C: send game.waiting + CLOSE connection (WS)
    destroy Pre
    Pre-xPre:am ded
    C->>C: Show "Joining game..."
    C-)P: OPEN connection (WS)
    P->>P: Add score and winner/loser to match object
    create participant Post as PostGame
    P-)Post:send full match object to game.over (NATS)
    P--)C: CLOSE connection (WS)
    Post->>Post: receive full match object
    create participant DB as DataBase
    Post->>DB: send data