%%{init:{"themeVariables": {
    "noteBkgColor":"#f4f4f4", 
    "noteTextColor":"black",
    "noteBorderColor":"#000",
    "fontFamily":"Arial"
  }
}}%%
sequenceDiagram
    title Tournament MS Architecture
    autonumber

    create actor U as User
    create participant L as Lobby
    U-)L: Open connection (WS)
    Note over L: Create lobby
    Note over L: Host joins
    Note over U: Show <br/>Lobby
    Note over L: Host invites friends
    Note over L: Set game rules
    Note over U: Show <br/>Bracket Placeholder
    Note over L: "Play"

    create participant T as Tournament
    L-)T: Send tournament request (NATS)
    Note over T: Create Bracket
    Note over T: Create tournamentObj 

    create participant GM as GameManager
    T-)GM: Send tournamentObj +<br/> bracketObj (NATS)
    destroy T
    T--)L: Send  tournamentObj +<br/> bracketObj (NATS)
    L--)U: Send bracketObj (WS)
    Note over U: Show Real Bracket
    Note over GM: PreGame
    Note over GM: Receive tournamentObj +<br/> bracketObj
    Note over GM: Start Routine
    %% Note over GM: Pre: Organise tournament (match order)
    
      
      create participant P as Pong
      GM-)P: Send gameObj (NATS)
      P--)L: Send "game.ready" +<br/> gameID (NATS)
      destroy L
      L--)U: Close connection +<br/> Send "game.ready" +<br/> gameID (WS)
    loop Tournament Routine
      U-)P: Open connection via gameID (WS)
      Note over P: Game
      P--)GM: Send updated gameObj (NATS)
      Note over GM: PostGame
      Note over GM: IF Continue Tournament
      GM-)P: Send next gameObj (NATS)
      P--)U: Send "game.ready" +<br/> gameID (WS)
      Note over GM: Circle back to Step 9


      create participant DB as Database
      GM-)DB: Send gameObj (NATS)
    end
      Note over GM: ELSE Tournament Over
      Note over GM: Process endgame
      Note over DB: Store result