on:
  # pull_request:
  #   branches:
  #   - main
  push:
    branches:
    - test
jobs:
  unit-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: run containers
        run: make test
      - name: cleanup
        run: make fclean
      